# Generated by Django 3.2.10 on 2022-05-11 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0009_software_remove_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvelcm',
            name='last_modified_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
